[build]
  command = "ng build --configuration=production"
  functions = "netlify/functions"  
  publish = "dist/browser"

[functions]
  node_bundler = "esbuild"  

[[plugins]]
  package = "@netlify/angular-runtime"